stages:
  - analysis
  - build
  - test

before_script:
  - hostname
  - whoami
# - pwd
  - git submodule sync --recursive
  - git submodule update --init --recursive

analysis-cppcheck:
  stage: analysis
  artifacts:
    name: analysis-cppcheck-logs
    when: always
    paths:
      - cppcheck/
  tags:
    - cppcheck
  script:
    - ./ci/analysis-cppcheck.sh

build-linux-gcc:
  stage: build
  tags:
    - linux
    - gcc
    - cmake
    - x86
    - systemc
  artifacts:
    paths:
      - ./examples/bootstrap/build_linux_gcc/bin/
      - ./examples/factory/build_linux_gcc/bin/
      - ./examples/systemc/build_linux_gcc/bin/
      - ./examples/tasks/build_linux_gcc/bin/
      - ./examples/sequence/build_linux_gcc/bin/
      - ./examples/subsequence/build_linux_gcc/bin/
      - ./examples/pipeline/build_linux_gcc/bin/
      - ./examples/openmp/build_linux_gcc/bin/
      - ./examples/cython_polar/build_linux_gcc/bin/
      - ./lib/aff3ct/build_linux_gcc/lib/
  script:
    - export EXAMPLES="bootstrap tasks systemc factory sequence subsequence pipeline openmp cython_polar"
    - export CXX="g++"
    - export CFLAGS="-Wall -funroll-loops -msse4.2 -Wno-deprecated-declarations"
    - export BUILD="build_linux_gcc"
    - source ./ci/tools/threads.sh
    - source ./ci/tools/aff3ct-git-version.sh
    - ./ci/build-linux-macos.sh

build-linux-clang:
  stage: build
  tags:
    - linux
    - clang
    - cmake
    - x86
    - systemc
  artifacts:
    paths:
      - ./examples/bootstrap/build_linux_clang/bin/
      - ./examples/factory/build_linux_clang/bin/
      - ./examples/systemc/build_linux_clang/bin/
      - ./examples/tasks/build_linux_clang/bin/
      - ./examples/sequence/build_linux_clang/bin/
      - ./examples/subsequence/build_linux_clang/bin/
      - ./examples/pipeline/build_linux_clang/bin/
      - ./examples/openmp/build_linux_clang/bin/
      - ./examples/cython_polar/build_linux_clang/bin/
  script:
    - export EXAMPLES="bootstrap tasks systemc factory sequence subsequence pipeline openmp cython_polar"
    - export CXX="clang++"
    - export CFLAGS="-Wall -Wno-overloaded-virtual -funroll-loops -msse4.2 -Wno-deprecated-declarations"
    - export BUILD="build_linux_clang"
    - source ./ci/tools/threads.sh
    - source ./ci/tools/aff3ct-git-version.sh
    - ./ci/build-linux-macos.sh

build-linux-gcc-4.8:
  stage: build
  tags:
    - linux
    - gcc-4.8
    - cmake
    - systemc
  artifacts:
    paths:
      - ./examples/bootstrap/build_linux_gcc-4.8/bin/
      - ./examples/factory/build_linux_gcc-4.8/bin/
      - ./examples/systemc/build_linux_gcc-4.8/bin/
      - ./examples/tasks/build_linux_gcc-4.8/bin/
      - ./examples/sequence/build_linux_gcc-4.8/bin/
      - ./examples/subsequence/build_linux_gcc-4.8/bin/
      - ./examples/pipeline/build_linux_gcc-4.8/bin/
      - ./examples/openmp/build_linux_gcc-4.8/bin/
      - ./examples/cython_polar/build_linux_gcc-4.8/bin/
  script:
    - export EXAMPLES="bootstrap tasks systemc factory sequence subsequence pipeline openmp cython_polar"
    - export CXX="g++-4.8"
    - export CFLAGS="-Wall -funroll-loops -msse4.2 -Wno-deprecated-declarations"
    - export BUILD="build_linux_gcc-4.8"
    - source ./ci/tools/threads.sh
    - source ./ci/tools/aff3ct-git-version.sh
    - ./ci/build-linux-macos.sh

build-linux-icpc:
  stage: build
  tags:
    - linux
    - icpc
    - cmake
    - x86
    - systemc
  artifacts:
    paths:
      - ./examples/bootstrap/build_linux_icpc/bin/
      - ./examples/factory/build_linux_icpc/bin/
      - ./examples/systemc/build_linux_icpc/bin/
      - ./examples/tasks/build_linux_icpc/bin/
      - ./examples/sequence/build_linux_icpc/bin/
      - ./examples/subsequence/build_linux_icpc/bin/
      - ./examples/pipeline/build_linux_icpc/bin/
      - ./examples/openmp/build_linux_icpc/bin/
      - ./examples/cython_polar/build_linux_icpc/bin/
  script:
    - export EXAMPLES="bootstrap tasks systemc factory sequence subsequence pipeline openmp cython_polar"
    - export CXX="icpc"
    - export CFLAGS="-Wall -funroll-loops -msse4.2 -Wno-deprecated-declarations -std=c++11"
    - export BUILD="build_linux_icpc"
    - source ./ci/tools/threads.sh
    - source ./ci/tools/aff3ct-git-version.sh
    - ./ci/build-linux-macos.sh

build-windows-gcc:
  stage: build
  tags:
    - windows
    - gcc
    - cmake
  artifacts:
    paths:
      - ./examples/bootstrap/build_windows_gcc/bin/
      - ./examples/factory/build_windows_gcc/bin/
      - ./examples/tasks/build_windows_gcc/bin/
      - ./examples/sequence/build_windows_gcc/bin/
      - ./examples/subsequence/build_windows_gcc/bin/
      - ./examples/pipeline/build_windows_gcc/bin/
      - ./examples/openmp/build_windows_gcc/bin/
      - ./examples/cython_polar/build_windows_gcc/bin/
  script:
    - set "EXAMPLES=bootstrap tasks factory sequence subsequence pipeline openmp cython_polar"
    - set "CFLAGS=-Wall -Wno-deprecated-declarations -funroll-loops -mavx"
    - set "BUILD=build_windows_gcc"
    - call ./ci/tools/threads.bat
    - call ./ci/tools/aff3ct-git-version.bat
    - ./ci/build-windows-gcc.bat

build-windows-msvc:
  stage: build
  tags:
    - windows
    - msvc
    - cmake
  artifacts:
    paths:
      - ./examples/bootstrap/build_windows_msvc/bin/
      - ./examples/factory/build_windows_msvc/bin/
      - ./examples/tasks/build_windows_msvc/bin/
      - ./examples/sequence/build_windows_msvc/bin/
      - ./examples/subsequence/build_windows_msvc/bin/
      - ./examples/pipeline/build_windows_msvc/bin/
      - ./examples/openmp/build_windows_msvc/bin/
      - ./examples/cython_polar/build_windows_msvc/bin/
  script:
    - set "EXAMPLES=bootstrap tasks factory sequence subsequence pipeline openmp cython_polar"
    - set "CFLAGS=-D_CRT_SECURE_NO_DEPRECATE /EHsc /arch:AVX"
    - set "BUILD=build_windows_msvc"
    - call ./ci/tools/threads.bat
    - call ./ci/tools/aff3ct-git-version.bat
    - ./ci/build-windows-msvc.bat

build-macos-clang:
  stage: build
  tags:
    - macos
    - apple-clang
    - cmake
    - x86
  artifacts:
    paths:
      - ./examples/bootstrap/build_macos_clang/bin/
      - ./examples/factory/build_macos_clang/bin/
      - ./examples/tasks/build_macos_clang/bin/
      - ./examples/sequence/build_macos_clang/bin/
      - ./examples/subsequence/build_macos_clang/bin/
      - ./examples/pipeline/build_macos_clang/bin/
      - ./examples/openmp/build_macos_clang/bin/
      - ./examples/cython_polar/build_macos_clang/bin/
  script:
    - export EXAMPLES="bootstrap tasks factory sequence subsequence pipeline openmp cython_polar"
    - export CXX="clang++"
    - export CFLAGS="-Wall -Wno-overloaded-virtual -funroll-loops -msse4.2"
    - export BUILD="build_macos_clang"
    - source ./ci/tools/threads.sh
    - source ./ci/tools/aff3ct-git-version.sh
    - ./ci/build-linux-macos.sh

test-linux-run-bootstrap:
  stage: test
  tags:
    - linux
    - sse4.2
  needs:
    - job: build-linux-gcc
      artifacts: true
    - job: build-linux-gcc-4.8
      artifacts: true
    - job: build-linux-clang
      artifacts: true
    - job: build-linux-icpc
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh bootstrap " " build_linux_gcc build_linux_gcc-4.8 build_linux_clang build_linux_icpc

test-linux-run-systemc:
  stage: test
  tags:
    - linux
    - sse4.2
    - systemc
  needs:
    - job: build-linux-gcc
      artifacts: true
    - job: build-linux-clang
      artifacts: true
    - job: build-linux-icpc
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh systemc " " build_linux_gcc build_linux_clang build_linux_icpc

test-linux-run-tasks:
  stage: test
  tags:
   - linux
   - sse4.2
  needs:
    - job: build-linux-gcc
      artifacts: true
    - job: build-linux-gcc-4.8
      artifacts: true
    - job: build-linux-clang
      artifacts: true
    - job: build-linux-icpc
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh tasks " " build_linux_gcc build_linux_gcc-4.8 build_linux_clang build_linux_icpc

test-linux-run-factory:
  stage: test
  tags:
    - linux
    - sse4.2
  needs:
    - job: build-linux-gcc
      artifacts: true
    - job: build-linux-gcc-4.8
      artifacts: true
    - job: build-linux-clang
      artifacts: true
    - job: build-linux-icpc
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh factory "-K 32 -N 128" build_linux_gcc build_linux_gcc-4.8 build_linux_clang build_linux_icpc

test-linux-run-sequence:
  stage: test
  tags:
    - linux
    - sse4.2
  needs:
    - job: build-linux-gcc
      artifacts: true
    - job: build-linux-gcc-4.8
      artifacts: true
    - job: build-linux-clang
      artifacts: true
    - job: build-linux-icpc
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh sequence "-K 32 -N 128" build_linux_gcc build_linux_gcc-4.8 build_linux_clang build_linux_icpc

test-linux-run-subsequence:
  stage: test
  tags:
    - linux
    - sse4.2
  needs:
    - job: build-linux-gcc
      artifacts: true
    - job: build-linux-gcc-4.8
      artifacts: true
    - job: build-linux-clang
      artifacts: true
    - job: build-linux-icpc
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh subsequence "-K 32 -N 128" build_linux_gcc build_linux_gcc-4.8 build_linux_clang build_linux_icpc

test-linux-run-cython_polar:
  stage: test
  tags:
    - linux
    - sse4.2
  needs:
    - job: build-linux-gcc
      artifacts: true
    - job: build-linux-gcc-4.8
      artifacts: true
    - job: build-linux-clang
      artifacts: true
    - job: build-linux-icpc
      artifacts: true
  script:
    ./ci/test-linux-macos-run.sh cython_polar " " build_linux_gcc build_linux_gcc-4.8 build_linux_clang build_linux_icpc

# test-linux-run-openmp:
#   stage: test
#   tags:
#     - linux
#     - sse4.2
#   needs:
#     - job: build-linux-gcc
#       artifacts: true
#     - job: build-linux-gcc-4.8
#       artifacts: true
#     - job: build-linux-clang
#       artifacts: true
#     - job: build-linux-icpc
#       artifacts: true
#   script:
#     - ./ci/test-linux-macos-run.sh openmp "-K 32 -N 128" build_linux_gcc build_linux_gcc-4.8 build_linux_clang build_linux_icpc

test-macos-run-bootstrap:
  stage: test
  tags:
   - macos
   - sse4.2
  needs:
    - job: build-macos-clang
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh bootstrap " " build_macos_clang

test-macos-run-tasks:
  stage: test
  tags:
   - macos
   - sse4.2
  needs:
    - job: build-macos-clang
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh tasks " " build_macos_clang

test-macos-run-factory:
  stage: test
  tags:
   - macos
   - sse4.2
  needs:
    - job: build-macos-clang
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh factory "-K 32 -N 128" build_macos_clang

test-macos-run-sequence:
  stage: test
  tags:
   - macos
   - sse4.2
  needs:
    - job: build-macos-clang
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh sequence "-K 32 -N 128" build_macos_clang

test-macos-run-subsequence:
  stage: test
  tags:
   - macos
   - sse4.2
  needs:
    - job: build-macos-clang
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh subsequence "-K 32 -N 128" build_macos_clang

test-macos-run-cython_polar:
  stage: test
  tags:
   - macos
   - sse4.2
  needs:
    - job: build-macos-clang
      artifacts: true
  script:
    - ./ci/test-linux-macos-run.sh cython_polar " " build_macos_clang

# test-macos-run-openmp:
#   stage: test
#   tags:
#    - macos
#    - sse4.2
#   needs:
#    - job: build-macos-clang
#      artifacts: true
#   script:
#     - ./ci/test-linux-macos-run.sh openmp "-K 32 -N 128" build_macos_clang

# test-windows-run-bootstrap:
#   stage: test
#   tags:
#    - windows
#    - avx
#   needs:
#    - job: build-windows-gcc
#      artifacts: true
#    - job: build-windows-msvc
#      artifacts: true
#   script:
#     - ./ci/test-windows-run.bat bootstrap " " build_windows_gcc build_windows_msvc

# test-windows-run-tasks:
#   stage: test
#   tags:
#    - windows
#    - avx
#   needs:
#    - job: build-windows-gcc
#      artifacts: true
#    - job: build-windows-msvc
#      artifacts: true
#   script:
#     - ./ci/test-windows-run.bat tasks " " build_windows_gcc build_windows_msvc

# test-windows-run-factory:
#   stage: test
#   tags:
#    - windows
#    - avx
#   needs:
#    - job: build-windows-gcc
#      artifacts: true
#    - job: build-windows-msvc
#      artifacts: true
#   script:
#     - ./ci/test-windows-run.bat factory "-K 32 -N 128" build_windows_gcc build_windows_msvc

# test-windows-run-openmp:
#   stage: test
#   tags:
#    - windows
#    - avx
#   needs:
#    - job: build-windows-gcc
#      artifacts: true
#    - job: build-windows-msvc
#      artifacts: true
#   script:
#     - ./ci/test-windows-run.bat openmp "-K 32 -N 128" build_windows_gcc build_windows_msvc

# test-windows-run-sequence:
#   stage: test
#   tags:
#    - windows
#    - avx
#   needs:
#    - job: build-windows-gcc
#      artifacts: true
#    - job: build-windows-msvc
#      artifacts: true
#   script:
#     - ./ci/test-windows-run.bat sequence "-K 32 -N 128" build_windows_gcc build_windows_msvc

# test-windows-run-subsequence:
#   stage: test
#   tags:
#    - windows
#    - avx
#   needs:
#    - job: build-windows-gcc
#      artifacts: true
#    - job: build-windows-msvc
#      artifacts: true
#   script:
#     - ./ci/test-windows-run.bat subsequence "-K 32 -N 128" build_windows_gcc build_windows_msvc

# test-windows-run-cython_polar:
#   stage: test
#   tags:
#    - windows
#    - avx
#   needs:
#    - job: build-windows-gcc
#      artifacts: true
#    - job: build-windows-msvc
#      artifacts: true
#   script:
#     - ./ci/test-windows-run.bat cython_polar " " build_windows_gcc build_windows_msvc

test-linux-wrap-cython_polar:
  stage: test
  tags:
   - linux
   - sse4.2
   - gcc
   - python3.6
  needs:
    - job: build-linux-gcc
      artifacts: true
  script:
    - cd examples/cython_polar
    - pip3 install --user -r requirements.txt
    - python3 setup.py build_ext -i
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../../lib/aff3ct/build_linux_gcc/lib
    - python3 -c "import codec_polar; print(codec_polar.py_generate_frozen_bits(10, 16, 20))"