# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget aff3ct::aff3ct-shared-lib aff3ct::aff3ct-static-lib)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target aff3ct::aff3ct-shared-lib
add_library(aff3ct::aff3ct-shared-lib SHARED IMPORTED)

set_target_properties(aff3ct::aff3ct-shared-lib PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "AFF3CT_POLAR_BIT_PACKING;AFF3CT_COLORS;AFF3CT_BACKTRACE;AFF3CT_EXT_STRINGS;AFF3CT_MULTI_PREC;MIPP_ENABLE_BACKTRACE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/include/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/cli/src/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/MIPP/src/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/rang/include/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/date/include/date/"
  INTERFACE_LINK_LIBRARIES "Threads::Threads"
)

# Create imported target aff3ct::aff3ct-static-lib
add_library(aff3ct::aff3ct-static-lib STATIC IMPORTED)

set_target_properties(aff3ct::aff3ct-static-lib PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "AFF3CT_POLAR_BIT_PACKING;AFF3CT_COLORS;AFF3CT_BACKTRACE;AFF3CT_EXT_STRINGS;AFF3CT_MULTI_PREC;MIPP_ENABLE_BACKTRACE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/include/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/cli/src/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/MIPP/src/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/rang/include/;/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/lib/date/include/date/"
  INTERFACE_LINK_LIBRARIES "Threads::Threads"
)

# Import target "aff3ct::aff3ct-shared-lib" for configuration "Release"
set_property(TARGET aff3ct::aff3ct-shared-lib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aff3ct::aff3ct-shared-lib PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/build/lib/libaff3ct-2.3.5-490-g555c239.so"
  IMPORTED_SONAME_RELEASE "libaff3ct-2.3.5-490-g555c239.so"
  )

# Import target "aff3ct::aff3ct-static-lib" for configuration "Release"
set_property(TARGET aff3ct::aff3ct-static-lib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(aff3ct::aff3ct-static-lib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/lab-yl/Documents/code/my_project_with_aff3ct/lib/aff3ct/build/lib/libaff3ct-2.3.5-490-g555c239.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
